

import { Milestone } from './milestone';

export var CHECKLIST: Milestone[] = [

// {id: 0, name: '',progress: 0,detail: "",notes:"",img:"",icon:""},
{id: 1, name: 'Copies adults and friends (like running when other children run)',progress: 0, detail: "This is detail for this milestone： Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id lectus non augue finibus feugiat et at ligula. Etiam ut felis id diam dictum sollicitudin feugiat a odio. In vel varius purus, vel consectetur tellus. Vivamus sed erat faucibus tellus euismod egestas ac sed felis. Mauris efficitur mattis nisl, a pretium quam tincidunt et. Donec egestas velit sed risus egestas sollicitudin. " ,notes:"This is the note for this milestone", img:"../../assets/images/milestone1.jpg", icon:"../../assets/images/staricons/1.png"},
{id: 2, name: 'Shows affection for friends without prompting',progress: 0,detail: "This is detail for this milestone： Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id lectus non augue finibus feugiat et at ligula. Etiam ut felis id diam dictum sollicitudin feugiat a odio. In vel varius purus, vel consectetur tellus. Vivamus sed erat faucibus tellus euismod egestas ac sed felis. Mauris efficitur mattis nisl, a pretium quam tincidunt et. Donec egestas velit sed risus egestas sollicitudin. ",notes:"This is the note for this milestone",img:"../../assets/images/milestone2.jpg", icon:"../../assets/images/staricons/2.png"},
{id: 3, name: 'Takes turns in games',progress: 0, detail: "This is detail for this milestone： Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id lectus non augue finibus feugiat et at ligula. Etiam ut felis id diam dictum sollicitudin feugiat a odio. In vel varius purus, vel consectetur tellus. Vivamus sed erat faucibus tellus euismod egestas ac sed felis. Mauris efficitur mattis nisl, a pretium quam tincidunt et. Donec egestas velit sed risus egestas sollicitudin. ",notes:"This is the note for this milestone",img:"../../assets/images/milestone3.jpg", icon:"../../assets/images/staricons/3.png"},
{id: 4, name: 'Shows concern for a crying friend',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/4.png"},
{id: 5, name:  'Understands the idea of "mine" and "his" or "hers"',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/5.png"},
{id: 6, name: 'Shows a wide range of emotions',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/6.png"},
{id: 7, name:  'Separates easily  from mom and dad',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/7.png"},
{id: 8, name: 'May get upset with major changes in routine',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/8.png"},
{id: 9, name: 'Dresses and undresses self ',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/8.png"},
{id: 10, name: 'Follows instructions with 2 or 3 steps',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/9.png"},
{id: 11, name: 'Can name most familiar things',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/10.png"},
{id: 12, name: 'Understands words like "in," "on," and "under"',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/11.png"},
{id: 13, name: 'Says first name, age, and sex',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/12.png"},
{id: 14, name: 'Names a friend',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/13.png"},
{id: 15, name: 'Says works like "I," "me,", "we,", and "you" and some plurals (cars, dogs, cats)',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/14.png"},
{id: 16, name: 'Talks well enough for strangers to understand most of the time',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/15.png"},
{id: 17, name: 'Carries on a conversation using 2 to 3 sentences',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/16.png"},
{id: 18, name:  'Can work toys with buttons, levers, and moving parts',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/17.png"},
{id: 19, name:  'Plays make-believe with dolls, animals, and people',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/18.png"},
{id: 20, name: 'Does puzzles with 3 or 4 pieces',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/19.png"},
{id: 21, name: 'Understands what "two" means',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/20.png"},
{id: 22, name: 'Copies a circle with a pencil or crayon',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/21.png"},
{id: 23, name: 'Turns book pages one at a time',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/22.png"},
{id: 24, name: 'Builds towers of more than 6 blocks',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/23.png"},
{id: 25, name: 'Screws and unscrews jar lids or turns door handle',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/24.png"},
{id: 26, name: 'Climbs well',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/25.png"},
{id: 27, name:  'Runs easily',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/26.png"},
{id: 28, name: 'Pedals a tricycle (3-wheeled bike)',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/27.png"},
{id: 29, name: 'Walks up and down stairs, one foot on each step',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/28.png"},
{id: 30, name: 'Points to show others something interesting (age 18-month milestone)',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/28.png"},
{id: 31, name: 'Plays well with two or three children in a group (age 4 milestone)',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/28.png"},
{id: 32, name: 'Practices using safety scissors (age 4 milestone) at school.',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/28.png"},
{id: 33, name: 'Tells a story (age 4 milestone) while pretending to read.',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/28.png"},
{id: 34, name: 'Shows independence (age 2 milestone) by trying to brush his own teeth.',progress: 0,detail: "",notes:"",img:"",icon:"../../assets/images/staricons/28.png"},
];