import { Page } from './page';

export var PAGES: Page[] = [
  {id: 1, img: '../../assets/images/homepage.jpg', progress: 0},
  {id: 2, img: '../../assets/images/p1.jpg',progress: 0},
  {id: 3, img: '../../assets/images/p2.jpg',progress: 0},
  {id: 4, img: '../../assets/images/p3.jpg',progress: 0},
  {id: 5, img: '../../assets/images/p4.jpg',progress: 0},
  {id: 6, img: '../../assets/images/p5.jpg',progress: 0},
  {id: 7, img: '../../assets/images/p6.jpg',progress: 0},
  {id: 8, img: '../../assets/images/p7.jpg',progress: 0},
  {id: 9, img: '../../assets/images/p8.jpg',progress: 0},
  {id: 10, img: '../../assets/images/p9.jpg',progress: 0},
  {id: 11, img: '../../assets/images/p10.jpg',progress: 0},
  {id: 12, img: '../../assets/images/p11.jpg',progress: 0},
  {id: 13, img: '../../assets/images/p12.jpg',progress: 0},
  {id: 14, img: '../../assets/images/p13.jpg',progress: 0},
  {id: 15, img: '../../assets/images/p14.jpg',progress: 0},
  {id: 16, img: '../../assets/images/p15.jpg',progress: 0},
  {id: 17, img: '../../assets/images/p16.jpg',progress: 0},
  {id: 18, img: '../../assets/images/p17.jpg',progress: 0},
  {id: 19, img: '../../assets/images/p18.jpg',progress: 0},
  {id: 20, img: '../../assets/images/p19.jpg',progress: 0},
  {id: 21, img: '../../assets/images/p20.jpg',progress: 0},
  {id: 22, img: '../../assets/images/p21.jpg',progress: 0},
  {id: 23, img: '../../assets/images/p22.jpg',progress: 0},
  {id: 24, img: '../../assets/images/p23.jpg',progress: 0},
  {id: 25, img: '../../assets/images/p24.jpg',progress: 0},
  {id: 26, img: '../../assets/images/p25.jpg',progress: 0},
  {id: 27, img: '../../assets/images/p26.jpg',progress: 0},
  {id: 28, img: '../../assets/images/p27.jpg',progress: 0},
  {id: 29, img: '../../assets/images/p28.jpg',progress: 0},
  {id: 30, img: '../../assets/images/p29.jpg',progress: 0},
  {id: 31, img: '../../assets/images/p30.jpg',progress: 0},
  {id: 32, img: '../../assets/images/p31.jpg',progress: 0},

  
];
